# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
use_frameworks!

target 'RightClickApp' do
 pod 'Eureka', '~> 1.5'
 pod "jot", :git => 'https://github.com/janiduw/jot.git'
end

target 'RightClickAppTests' do

end

target 'RightClickAppUITests' do

end

